version: "3.8"

services:
#mysql Service
  mysqldb:
    image: mysql:8.0.1
    container_name: db_oral
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

#server Service
  server:    
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: oral_server
    restart: on-failure
    env_file: ./server/.env
    ports:
      - "6868:8080"
    volumes:
      - .m2:/root/.m2
    depends_on:
      - mysqldb
    networks:
      - app-network

#production
#client Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: oral_client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network


#phpMyAdmin Service
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadminOral
      ports:
        - "8081:80"
      environment:
        PMA_HOST: mysqldb
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: root
      networks:
        - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge



