
version: "3.3"

services:
#mysql Service
  mysqldb:
    image: mysql:8.0.1
    container_name: oral_db
    restart: unless-stopped
    env_file: ./server/.env.dev
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    profiles:
      - dev
      - prod

#server Service
  server:    
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: oral_server
    restart: on-failure
    env_file: 
      - ./server/.env.dev
      - ./server/.env.prod
    ports:
      - "6868:8080"
    volumes:
      - ./server:/app
      - server-cache:/root/.m2
    networks:
      - app-network
    profiles:
      - dev
      - prod
  
  #client Service
  client:
    build: ./client
    env_file: 
      - ./client/.env.dev
      - ./client/.env.prod
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - client-cache:/root/.cache/vite
    profiles:
      - dev
      - prod

#phpMyAdmin Service
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadminOral
      ports:
        - "8082:80"
      environment:
        PMA_HOST: mysqldb
        PMA_PORT: 3306
      networks:
        - app-network
      profiles:
        - dev

volumes:
  client-cache:
  server-cache:
  db_data:

networks:
  app-network:
    driver: bridge