version: "3.3"

services:
#mysql Service
  mysqldb:
    image: mysql:8.0.1
    container_name: oral_db
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

#server Service
  server:    
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: oral_server
    restart: on-failure
    env_file: ./server/.env
    ports:
      - "6868:8080"
    volumes:
      - ./server:/app
      - server-cache:/root/.m2
    depends_on:
      - mysqldb
    networks:
      - app-network
  
  #client Service
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - client-cache:/root/.cache/vite

#phpMyAdmin Service
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadminOral
      ports:
        - "8081:80"
      environment:
        PMA_HOST: mysqldb
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: root
      networks:
        - app-network

volumes:
  client-cache:
  server-cache:
  mysql-data:

networks:
  app-network:
    driver: bridge



